### ISSUE TITLE
User Stats on Profile Page

### ISSUE THREAD

**Issue by arjunsv** [medtech-berkeley/emerge-learning#49]
**Features**
1.) Points/Rankings (e.g. Rank #1 globally, Rank #5 in Myanmar)
2.) Tag proficiency (Distribution graph of proficiency in each tag (subject)
3.) Activity (Line graph of questions answered per day)

**NOTES:**
Take a look at the existing stats function in views
Most of the back-end functionality exists. Work will be mostly writing views, query functions, and front-end UI.

**Comment by kevkang** [comment]
So this requires a little clarification: in terms of points, I've just been treating each question as 1 "point". This feels wrong with the sample numbers given.
Also, I think features 2/3 are done, we just need to do 1, which would I guess be a "badge"?
